version: '3'

services:
  web:
    image: zzde/wxapp
    volumes:
      - .:/wxapp
      - django_static:/wxapp/static
      - media:/wxapp/media
    ports:
      - 8000:8000
    environment:
      - REDIS_DB_HOST=192.168.65.1
      - REDIS_DB_PORT=3306
    # build: .
    command: ./configs/bin/web.sh
    networks:
      - wxapp_network

  worker:
    image: zzde/wxapp
    # build: .
    environment:
      - REDIS_DB_HOST=192.168.65.1
      - REDIS_DB_PORT=3306
    volumes:
      - .:/wxapp
    command: ./configs/bin/celery.sh
    networks:
      - wxapp_network

networks:
  wxapp_network:

volumes:
  django_static:
  media:
